Repository ToucanToco/releaseman, pull requests merged in 2019-01, with the labels that each got.

#26 Feature :: Actions params
  src/actions/create-branch.js
  src/actions/create-labels.js
  src/actions/create-pull-request.js
  src/actions/create-release.js
  src/actions/delete-branch.js
  src/actions/find-pull-request.js
  src/actions/find-release-pull-request.js
  src/actions/get-branch-existence.js
  src/actions/get-changelog.js
  src/actions/get-labels.js
  src/actions/get-latest-release.js
  src/actions/get-next-release.js
  src/actions/get-pull-request-labels.js
  src/actions/get-pull-request.js
  src/actions/get-release-branch.js
  src/actions/get-releases-existence.js
  src/actions/index.js
  src/actions/merge-branches.js
  src/actions/merge-pull-request.js
  src/actions/run-changes.js
  src/actions/run-continue.js
  src/actions/run-feature-finish.js
  src/actions/run-feature-publish.js
  src/actions/run-feature-start.js
  src/actions/run-feature.js
  src/actions/run-fix-finish.js
  src/actions/run-fix-publish.js
  src/actions/run-fix-start.js
  src/actions/run-fix.js
  src/actions/run-help.js
  src/actions/run-hotfix-finish.js
  src/actions/run-hotfix-publish.js
  src/actions/run-hotfix-start.js
  src/actions/run-hotfix.js
  src/actions/run-init.js
  src/actions/run-release-finish.js
  src/actions/run-release-start.js
  src/actions/run-release.js
  src/actions/run-task.js
  src/actions/run.js
  src/actions/save-state.js
  src/actions/skip-task.js
  src/actions/start.js
  src/actions/update-branch.js
  src/actions/update-pull-request-labels.js
  src/actions/update-pull-request.js
  src/github.js
  src/mutations/assign-data.js
  src/mutations/index.js
  src/mutations/patch-data.js
  src/mutations/set-config.js
  src/mutations/set-data.js
  src/mutations/set-task-index.js
  src/store.js
Labels: feature

#27 Fix :: Errors during refactos
  src/actions/delete-branch.js
  src/actions/get-pull-request.js
  src/actions/run-continue.js
  src/actions/run-feature-finish.js
  src/actions/run-fix-finish.js
  src/actions/run-fix.js
  src/actions/run-hotfix-finish.js
  src/actions/run-hotfix.js
  src/actions/run-release-finish.js
  src/actions/run-release.js
  src/actions/run-task.js
  src/actions/skip-task.js
  src/actions/start.js
  src/github.js
  src/index.js
  src/store.js
  yarn.lock
Labels: bug

#28 Feature :: Simple indexes
  src/actions/run-changes.js
  src/actions/run-feature-finish.js
  src/actions/run-feature-publish.js
  src/actions/run-feature-start.js
  src/actions/run-fix-finish.js
  src/actions/run-fix-publish.js
  src/actions/run-fix-start.js
  src/actions/run-hotfix-finish.js
  src/actions/run-hotfix-publish.js
  src/actions/run-hotfix-start.js
  src/actions/run-init.js
  src/actions/run-release-finish.js
  src/actions/run-release-start.js
  src/store.js
Labels: feature

#30 Fix :: Typo in the feature finish command
  src/actions/run-feature-finish.js
Labels: bug

#31 Feature :: Update dependencies
  package.json
  rollup.config.js
  yarn.lock
Labels: feature

#33 Fix :: Typo in release finish
  src/actions/run-release-finish.js
Labels: bug

#34 Hotfix :: Latest beta base
  package.json
  src/actions/run-init.js
Labels: bug

#35 Doc :: add typical workflow in README
  README.md
Labels: doc
